182 delete label
kod-man/reminder-client pull request #185
Opened 2023-04-04 08:53 UTC by EkrlDev

2023-04-05 19:21 UTC, kod-man requested changes

2023-04-07 09:07 UTC, kod-man requested changes

2023-04-07 09:07 UTC, kod-man commented on src/modals/AddItemModal.tsx
> +            tooltipLabel === "Project"
If you use plural naming for project, dont need a check here

2023-04-07 09:07 UTC, kod-man commented on src/modals/AddItemModal.tsx
> +      <MyTooltip
same as above

2023-04-07 09:07 UTC, kod-man commented on src/modals/AddItemModal.tsx
> +          tooltipLabel === "Project"
same as above

2023-04-07 10:41 UTC, EkrlDev commented on src/components/Navbar/Components/DrawerComponent.tsx
> +            <AddItemModal tooltipLabel="Project" />
label={
          tooltipLabel === "Project"
            ? `Add ${tooltipLabel.toLowerCase()}` ===> last letter is not deleted
            : `Add new ${title.toLowerCase()}` ==> last letter deleted
        }
last chars are not deleted if its a "Project" label

2023-04-07 11:32 UTC, kod-man commented on src/components/Navbar/Components/DrawerComponent.tsx
> +            <AddItemModal tooltipLabel="Project" />
Why do we need to check project?

2023-04-07 15:24 UTC, kod-man approved these changes

2023-04-07 15:25 UTC, merged