33 create profile menu
kod-man/reminder-client pull request #36
Opened 2022-12-22 16:20 UTC by muratcan23

2022-12-23 14:22 UTC, kod-man requested changes

2022-12-23 14:22 UTC, kod-man commented on src/pages/Home/Components/ProfileMenu.tsx
> +        <MenuItem
Why don't you create a component for MenuItem? You are repeating yourself. You should obey the Don't Repeat Yourself (DRY) rule.

2022-12-24 13:06 UTC, kod-man requested changes

2022-12-24 13:06 UTC, kod-man commented on src/pages/Home/Components/ProfileMenu.tsx
> +              <Box>
Box is not needed

2022-12-24 13:06 UTC, kod-man commented on src/pages/Home/Components/ProfileMenu.tsx
> +        <MenuItem
You can use Profile card components once again for log out

2022-12-24 13:06 UTC, kod-man commented on src/pages/Home/Components/ProfileMenu.tsx
> +        <MenuItem
Because the only difference is the divider

2022-12-24 13:39 UTC, muratcan23 commented on src/pages/Home/Components/ProfileMenu.tsx
> +                </Flex>
i feel ashamed :(

2022-12-24 13:42 UTC, muratcan23 commented on src/pages/Home/Components/ProfileCards.tsx
> +const ProfileCards: FC<CardProps> = ({ Icon, text }) => {
this will push me a little bit.

2022-12-25 12:18 UTC, kod-man requested changes

2022-12-25 12:18 UTC, kod-man commented on src/pages/Home/Components/ProfileMenu.tsx
> +        <ProfileCards text={"Logout"} Icon={FiSettings} />
no need to add curly braces {}

2022-12-25 12:18 UTC, kod-man commented on src/pages/Home/Components/ProfileMenu.tsx
> +                  <Text fontSize="xs" color="grey">
grey ? should not it be gray?

2022-12-25 12:18 UTC, kod-man commented on src/pages/Home/Components/ProfileCards.tsx
> +const ProfileCards: FC<CardProps> = ({ Icon, text }) => {
<img width="470" alt="Screenshot 2022-12-25 at 13 17 11" src="https://user-images.githubusercontent.com/54946794/209467603-a7e18ccf-0c07-4d97-be94-37d25933794e.png">

2022-12-25 12:18 UTC, kod-man commented on src/pages/Home/Components/ProfileCards.tsx
> +const ProfileCards: FC<CardProps> = ({ Icon, text }) => {
try this one

2022-12-25 13:02 UTC, kod-man approved these changes

2022-12-25 13:02 UTC, merged